name: Automated Push

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours (00:00 and 12:00 UTC)

jobs:
  push_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <— required so the workflow can push commits
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # we'll use the token explicitly
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit via GitHub Actions" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
